config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :post_categories
  end

  SpudBlogConfig.each do |config|
    blog_key = config.key

    namespace :admin do
      resources :posts, :path => blog_key, :blog_key => blog_key do
        match :preview, on: :collection, via: [:post, :patch]
      end
    end

    scope config.path do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)' => 'posts#category',
        :as => "#{blog_key}_category",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)' => 'posts#archive',
        :as => "#{blog_key}_archive",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Blog Post Category + Archive
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'posts',
        :action => 'category',
        :as => "#{blog_key}_category_archive",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'posts', :action => 'filter', :blog_key => blog_key

      # Blog Posts
      get '/(page/:page)' => 'posts#index',
        :as => "#{blog_key}_posts",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      get ':id' => 'posts#show', :as => "#{blog_key}_post", :blog_key => blog_key
    end
  end

end

app/controllers/admin/post_categories_controller.rb
class Admin::PostCategoriesController < Admin::ApplicationController

  layout false
  respond_to :html, :json

  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @post_categories = SpudPostCategory.ordered
    respond_with @post_categories
  end

  def edit
    respond_with @post_category
  end

  def update
    if @post_category.update(category_params)
      flash.now[:notice] = 'Post Category was successfully updated'
      respond_with @post_category, location: admin_post_categories_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def new
    @post_category = SpudPostCategory.new
    respond_with @post_category
  end

  def create
    @post_category = SpudPostCategory.new(category_params)
    if @post_category.save
      flash.now[:notice] = 'Post Category was successfully created'
      respond_with @post_category, location: admin_post_categories_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    if @post_category.destroy
      flash.now[:notice] = 'Post Category was successfully deleted'
      @post_categories = SpudPostCategory.ordered
      render 'index'
    else
      respond_with @post_category, location: admin_post_categories_path
    end
  end

  private

  def find_category
    @post_category = SpudPostCategory.find(params[:id])
  end

  def category_params
    params.require(:spud_post_category).permit(:name)
  end

end

app/helpers/admin/post_categories_helper.rb
module Admin::PostCategoriesHelper
end

app/views/admin/post_categories/_category.html.erb
<%= content_tag :tr, :class => 'spud-blog-category-manager-item', 'data-id' => category.id do %>
  <td><%= category.name %></td>
  <td class="table-actions">
    <%= link_to 'Edit', edit_admin_post_category_path(category), :class => 'btn btn-xs btn-default spud-blog-category-edit' %>
    <%= link_to 'Delete', admin_post_category_path(category), :class => 'btn btn-xs btn-danger spud-blog-category-delete' %>
  </td>
<% end %>

app/views/admin/post_categories/_form.html.erb
<%= form_for @post_category, :url => (@post_category.new_record? ? admin_post_categories_path : admin_post_category_path(@post_category)), :html => {:class => 'form-horizontal spud-post-category-form'} do |f| %>

	<%= tb_form_errors(@post_category) %>

  <div class="form-group">
    <%= f.label :name, :required => true, :class=> "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class=>'form-control' %>
    </div>
  </div>

<% end %>

app/views/admin/post_categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/post_categories/index.html.erb
<div class="spud-blog-category-manager">
	<%= link_to "New Post Category", new_admin_post_category_path, :class => "btn btn-sm btn-primary spud-blog-category-add-new", :title => "New Post Category" %>
  <table class="table table-striped table-condensed spud-blog-category-manager-table">
    <tbody>
      <%= render :partial => 'category', :collection => @post_categories %>  
    </tbody>
  </table>
</div>

app/views/admin/post_categories/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_post_categories_path} %>