config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :post_categories
  end

  SpudBlogConfig.each do |config|
    blog_key = config.key

    namespace :admin do
      resources :posts, :path => blog_key, :blog_key => blog_key do
        match :preview, on: :collection, via: [:post, :patch]
      end
    end

    scope config.path do

      # Blog Post Categories
      get 'category/:category_url_name(/page/:page)' => 'posts#category',
        :as => "#{blog_key}_category",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Blog Post Archives
      get 'archive/:archive_date(/page/:page)' => 'posts#archive',
        :as => "#{blog_key}_archive",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Blog Post Category + Archive
      get 'category/:category_url_name/:archive_date(/page/:page)',
        :controller => 'posts',
        :action => 'category',
        :as => "#{blog_key}_category_archive",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      # Category/Archive filtering
      post '/', :controller => 'posts', :action => 'filter', :blog_key => blog_key

      # Blog Posts
      get '/(page/:page)' => 'posts#index',
        :as => "#{blog_key}_posts",
        :blog_key => blog_key,
        :defaults => {:page => 1}

      get ':id' => 'posts#show', :as => "#{blog_key}_post", :blog_key => blog_key
    end
  end

end

app/models/tb_core/spud_post_model.rb
class TbCore::SpudPostModel < ActiveRecord::Base
  include TbRedirects::HasRedirects

  self.table_name = 'spud_posts'

  has_many :spud_post_categories_posts,
    foreign_key: :spud_post_id,
    inverse_of: :spud_post
  has_many :categories,
    class_name: 'SpudPostCategory',
    through: :spud_post_categories_posts,
    source: :spud_post_category,
    inverse_of: :posts

  belongs_to :author, class_name: 'SpudUser', foreign_key: 'spud_user_id'

  scope :blog_posts, -> { for_blog('blog') }
  scope :news_posts, -> { for_blog('news') }
  scope :for_blog, ->(key) { where(blog_key: key) }
  scope :visible, -> { where('visible = true AND published_at <= ?', Time.now.utc) }
  scope :ordered, -> { order('published_at desc') }

  scope :search, ->(term) { where('title LIKE ?', "%#{term}%") }
  scope :for_user, ->(user) {
    if Spud::Blog.query_for_user.present?
      where(Spud::Blog.query_for_user.call(user))
    else
      where({})
    end
  }

  validates :title, :content, :published_at, :spud_user_id, presence: true
  validates :url_name, presence: true, uniqueness: true, format: { with: /\A[\w\-]+\z/, message: 'must contain only letters, numbers, and dashes' }
  validates :url_name, uniqueness: true
  before_validation :set_url_name
  before_validation :set_identifier

  def self.for_spud_site(_spud_site_id)
    ActiveSupport::Deprecation.warn 'SpudBlog.for_spud_site is deprecated and will be removed in the future'
    return all()
  end

  def self.recent_posts(limit = 5)
    return where('visible = ? AND published_at <= ?', true, Time.now.utc).order('published_at desc').limit(limit)
  end

  def self.recent_blog_posts(limit = 5)
    return blog_posts.recent_posts(limit)
  end

  def self.recent_news_posts(limit = 5)
    return news_posts.recent_posts(limit)
  end

  def self.from_archive(date_string)
    date = Date.strptime(date_string, '%Y-%b')
    return where(published_at: date..date.end_of_month)
  rescue StandardError
    logger.debug 'fallback'
    return where('')
  end

  def is_news
    ActiveSupport::Deprecation.warn ':is_news is deprecated. Please rely on the :blog_key column stead.', caller
    return self[:is_news]
  end

  def self.months_with_public_posts
    records = SpudPost.select('Extract(Month from published_at) as published_month, Extract(Year from published_at) as published_year').where('visible = ? AND published_at < ?', true, DateTime.now).group('published_month, published_year').order('published_year desc, published_month desc')
    begin
      return records.collect { |r| Date.new(r[:published_year].to_i, r[:published_month].to_i) }
    rescue Exception => e
      logger.fatal "Exception occurred while fetching post archive dates:\n #{e}"
      return []
    end
  end

  # def postprocess_content
  #   template = Liquid::Template.parse(content)
  #   self.content_processed = template.render()
  # end
  #
  # def content_processed
  #   postprocess_content if self[:content_processed].blank?
  #   self[:content_processed]
  # end

  # def content_processed=(content)
  #   self[:content_processed] = content
  # end

  def content_processed
    ActiveSupport::Deprecation.warn '#content_processed is deprecated. Use #content instead.'
    content
  end

  def display_date
    return published_at.strftime('%b %d, %Y')
  end

  def is_public?
    return (published_at < DateTime.now) && visible
  end

  def is_private?
    return !is_public?
  end

  def category_names
    return categories.collect(&:name).join(', ')
  end

  def author_name
    if custom_author.present?
      custom_author
    elsif author.present?
      author.full_name
    else
      ''
    end
  end

  private

  def set_url_name
    self.url_name = title.parameterize if url_name.blank?
  end

  def set_identifier
    self.identifier = SecureRandom.uuid if identifier.blank?
    return true
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  include BlogUrlHelpers
  include RenderPostAction

  respond_to :html, :xml, :json
  before_action :load_blog
  before_action :find_post, only: [:edit, :update, :destroy]
  around_action :create_redirect_if_necessary, only: :update

  def index
    @posts = SpudPost.for_blog(params[:blog_key]).ordered.paginate(page: params[:page], per_page: 15)
    @posts = @posts.search(params[:search]) if params[:search]
    respond_with @posts
  end

  def edit
    respond_with @post
  end

  def show
  end

  def update
    flash[:notice] = 'Post was successfully updated.' if @post.update(post_params)
    respond_with @post, location: admin_posts_path
  end

  def new
    @post = SpudPost.new(published_at: Time.zone.now, spud_user_id: current_user.id)
    respond_with @post
  end

  def create
    @post = SpudPost.new(post_params)
    @post.blog_key = params[:blog_key]
    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with @post, location: admin_posts_path
  end

  def destroy
    flash[:notice] = 'Post was successfully deleted.' if @post.destroy
    respond_with @post, location: admin_posts_path
  end

  def preview
    @post = if params[:post_id]
              SpudPost.find_by!(id: params[:post_id])
            else
              SpudPost.new
            end
    @post.assign_attributes(post_params)
    render_post_action :show, controller: :posts, layout: @config.layout
  end

  private

  def find_post
    @post = SpudPost.find(params[:id])
    if @post.blank?
      flash[:error] = 'Post not found!'
      redirect_to(admin_posts_path) && (return false)
    end
  end

  def post_params
    permitted = [:published_at, :title, :content, :spud_user_id, :url_name, :visible, :comments_enabled, :meta_keywords, :meta_description, :content_format, :custom_author, category_ids: []]
    permitted += Spud::Blog.permitted_attributes if Spud::Blog.permitted_attributes.present?
    p = params.require(:spud_post).permit(permitted)
    p[:updated_at] = DateTime.now
    return p
  end

  def load_blog
    @config = SpudBlogConfig.find(params[:blog_key])
    if @config.blank?
      redirect_to admin_root_path
      return false
    else
      act_as_app "#{@config.name} Posts".parameterize.underscore.to_sym
      add_breadcrumb "#{@config.name} Posts", admin_posts_path(blog_key: @config.key)
    end
  end

  # Create a redirect if the post URL has changed
  #
  # Normally this sort of thing might belong in a model after_update hook, but the model
  # layer has no knowledge of URL helpers.
  #
  def create_redirect_if_necessary
    @_redirect_source = post_path(@post.url_name, blog_key: @post.blog_key, only_path: true)
    yield
  ensure
    if @post.errors.empty?
      @_redirect_destination = post_path(@post.url_name, blog_key: @post.blog_key, only_path: true)
      if @_redirect_source != @_redirect_destination
        TbRedirect.create_smart(source: @_redirect_source,
                                destination: @_redirect_destination,
                                created_by: 'blog',
                                owner: @post)
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include BlogUrlHelpers
  include RenderPostAction

  respond_to :html, :json, :rss

  before_action :load_blog
  before_action :load_page_number, only: [:index, :archive, :category]
  before_action :find_post, only: [:show, :create_comment]

  def index
    @posts = SpudPost.for_user(current_user).visible.for_blog(params[:blog_key]).ordered.paginate(page: @page_number, per_page: Spud::Blog.config.posts_per_page)
    @posts = @posts.search(params[:search]) if params[:search]
    respond_with @posts do |format|
      format.html do
        render_post_action :index
      end
    end
  end

  # The sole purpose of this action is to redirect from a POST to an seo-friendly url
  def filter
    if params[:category_url_name].present? && params[:archive_date].present?
      redirect_to post_category_archive_path(params[:category_url_name], params[:archive_date])
    elsif params[:category_url_name].present?
      redirect_to post_category_path(params[:category_url_name])
    elsif params[:archive_date].present?
      redirect_to post_archive_path(params[:archive_date])
    else
      redirect_to posts_path
    end
  end

  def category
    if @post_category = SpudPostCategory.find_by(url_name: params[:category_url_name])
      @posts = @post_category.posts.for_user(current_user).visible.for_blog(params[:blog_key]).from_archive(params[:archive_date]).ordered.paginate(page: @page_number, per_page: Spud::Blog.config.posts_per_page)
    else
      redirect_to posts_path
      return
    end
    respond_with @posts do |format|
      format.html { render_post_action :index }
    end
  end

  def archive
    @posts = SpudPost.for_user(current_user).visible.for_blog(params[:blog_key]).from_archive(params[:archive_date]).paginate(page: @page_number, per_page: Spud::Blog.config.posts_per_page)
    respond_with @posts do |format|
      format.html { render_post_action :index }
    end
  end

  def show
    respond_with @post do |format|
      format.html { render_post_action :show }
    end
  end

  private

  def find_post
    @post = SpudPost.for_user(current_user).for_blog(params[:blog_key]).where(url_name: params[:id]).first
    raise TbCore::NotFoundError, item: 'post' if @post.blank? || @post.is_private?
  end

  def load_page_number
    page = 1
    if params[:page].present?
      page = params[:page].to_i
      if page.to_s != params[:page].to_s
        if page > 1
          redirect_to(posts_path(page: page), status: :moved_permanently) && return
        else
          redirect_to(posts_path(page: nil), status: :moved_permanently) && return
        end
      end
    end
    @page_number = page
  end

  def load_blog
    @config = SpudBlogConfig.find(params[:blog_key])
    if @config.blank?
      raise TbCore::NotFoundError(item: 'blog')
    else
      self.class.layout(@config.layout)
    end
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper

  def options_for_parent_category(parent_id = 0)
    if @categories[parent_id]
      return @categories[parent_id].collect do |c|
        opts = [c.name, c.id]
        opts += options_for_parent_category(c.id)
      end
    else
      return []
    end
  end

  def link_to_disqus_comment_count(post)
    # TODO: It would be great to link directly to the thread
    #   ie: https://myblog.disqus.com/admin/moderate/#/all/search/thread:4584301535
    #
    # However, we do not know the thread ID at this time. We may be able to fetch it
    # via the Disqus JavaScript API.
    #
    return link_to 'Comments', "https://#{Spud::Blog.disqus_shortname}.disqus.com/admin/moderate/#/all", target: :blank, class: 'disqus-comment-count',
                                                                                                         data: { disqus_identifier: post.identifier }
  end

end

app/views/admin/posts/_category.html.erb
<%= content_tag :li, :class => 'spud_post_form_category', 'data-id' => category.id do %>
	<%= check_box_tag 'spud_post[category_ids][]', category.id, @post.category_ids.include?(category.id), :id => "spud_post_category_#{category.id}" %>
	<%= label_tag "spud_post_category_#{category.id}", category.name %>
<% end %>

app/views/admin/posts/_custom_fields.html.erb
<!-- 
  override me to supply custom form fields!
  app/views/admin/posts/_custom_fields.html.erb
  
  <h4>My Fields</h4>
  <div class="spud_post_form_row">
    ...etc
  </div>
-->

app/views/admin/posts/_form.html.erb
<%= tb_form_errors(@post)%>

<div class="form-group">
  <div class="col-sm-12">
  	<%= f.label :title, :required => true,:class=> "control-label" %>
  	<%= f.text_field :title, :class=>'form-control spud-post-title', :placeholder => "Enter title here" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-12">
  	<%= f.label :content %>
    <%= f.text_area :content, :class => 'tinymce form-control' %>
  </div>
</div>

<h4>Advanced</h4>

<% if @current_user.super_admin %>
	<div class="form-group">
	  <%= f.label :spud_user_id, 'Author', :class => "col-sm-2 control-label" %>
	  <div class="col-sm-10">
	    <%= f.select :spud_user_id, options_for_select(SpudUser.ordered.collect{|user| [user.full_name, user.id]}, @post.spud_user_id), {}, :class => 'form-control' %>
	  </div>
	</div>
<% else %>
	<%= f.hidden_field :spud_user_id %>
<% end %>
<div class="form-group">
	<%= f.label :custom_author, 'Custom Author Display', :class => "col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%= f.text_field :custom_author, :class=>'form-control', :placeholder => 'Author Display' %>
	</div>
</div>
<div class="form-group">
	<%= f.label :visible, :class => 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<label class="radio-inline" for="spud_post_visible_true">
			<%= f.radio_button :visible, true %> Yes
		</label>
		<label class="radio-inline" for="spud_post_visible_false">
			<%= f.radio_button :visible, false %> No
		</label>
	</div>
</div>

<div class="form-group">
	<%= f.label :comments_enabled, 'Enable Comments', :class => 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<label class="radio-inline" for="spud_post_comments_enabled_true">
			<%= f.radio_button :comments_enabled, true %> Yes
		</label>
		<label class="radio-inline" for="spud_post_comments_enabled_false">
			<%= f.radio_button :comments_enabled, false %> No
		</label>
	</div>
</div>

<div class="form-group">
	<%= f.label :published_at, 'Publish Date', :class => 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.datetime_select :published_at, {:ampm => true, :minute_step => 5, :order => [:month, :day, :year, :hour, :minute]}, {:class => 'form-control post-published-at-picker'} %>
	</div>
</div>

<div class="form-group">
  <%= label_tag :categories, 'Categories', :class => "col-sm-2 control-label" %>
  <div class="col-sm-10">
		<input type="hidden" name="spud_post[category_ids][]" value="" />
		<ul class="spud-post-categories-list">
			<%= render :partial => '/admin/posts/category', :collection => SpudPostCategory.ordered %>
		</ul>
		<%= link_to 'Add Category', new_admin_post_category_path, :class => 'btn btn-xs btn-primary spud-post-add-category' %>
  </div>
</div>

<%= render :partial => '/admin/posts/custom_fields', :locals => {:f => f} %>

<h4>Meta Data</h4>

<div class="form-group">
  <%= f.label :url_name, :required => true, :class=> "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :url_name, :class=>'form-control spud-post-url-name', :placeholder => 'Optional' %>
    <a href="#" class="btn btn-default spud-post-url-name-regen" title="Regenerate URL Slug">
      <span class="glyphicon glyphicon-refresh"></span>
    </a>
  </div>
</div>

<div class="form-group">
  <%= f.label :meta_keywords, :required => true, :class=> "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :meta_keywords, :class=>'form-control', :placeholder => 'Optional' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :meta_description, :required => true, :class=> "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :meta_description, :class=>'form-control', :placeholder => 'Optional' %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Save Post", :class => "btn btn-primary", "data-loading-text" => "Saving..." %>
    <%= f.submit "Preview", :class => "btn btn-info btn-preview", data: { loading_text: 'Please Wait...' } %> or
    <%= link_to "Cancel", request.referer, :class => "btn btn-default" %>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(spud.admin.posts.edit);
</script>

app/views/admin/posts/edit.html.erb
<%= tb_form_for @post,
	url: admin_post_path(@post),
	remote: true,
	data: {
		errors: :inline,
		success: admin_posts_path,
		preview_action: admin_post_preview_path(@post)
	},
	html: { :class => 'form-horizontal' } do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>

app/views/admin/posts/index.html.erb
<%= content_for :data_controls do %>
  <%= form_tag admin_posts_path, :method => :get, :class => 'form-inline' do %>
    <div class="form-group">
      <div class="input-group">
        <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
        <%= text_field_tag 'search', params[:search], :placeholder => 'Search', :class => 'form-control' %>
        <% if params[:search] %>
          <div class="input-group-addon">
            <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), admin_posts_path %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= link_to "Manage Categories", admin_post_categories_path, :class => 'btn btn-default spud-blog-manage-categories', :title => 'Manage Categories' %>
      <% if Spud::Blog.disqus_shortname %>
			 <%= link_to "Manage Comments", "https://#{Spud::Blog.disqus_shortname}.disqus.com/admin/moderate/#/all", :target => :blank, :class => 'btn btn-default', :title => 'Manage Comments' %>
      <% end %>
			<%= link_to "New Post", new_admin_post_path, :class => "btn btn-primary", :title => "New Post" %>
    </div>
  <% end %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Title</th>
					<th>Author</th>
					<th>Published At</th>
          <% if Spud::Blog.disqus_shortname %>
            <th>Comments</th>
          <% end %>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<% cache @posts do %>
					<% @posts.each do |post| %>
						<% cache post do %>
							<tr>
								<td>
									<%= link_to post.title, post_path(post.url_name), :target => :blank %>
									<% if !post.visible? %>
										<span class="badge">Draft</span>
									<% end %>
								</td>
								<td><%= post.author_name %></td>
								<td><%= post.published_at.strftime('%m/%d/%Y') %></td>
                <% if Spud::Blog.disqus_shortname %>
								  <td>
                    <%= link_to_disqus_comment_count(post) %>
                  </td>
                <% end %>
								<td class="table-actions">
									<%= link_to 'Edit', edit_admin_post_path(post), :class => 'btn btn-sm btn-default' %>
									<%= link_to 'Delete', admin_post_path(post), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this post?'}, :class => 'btn btn-sm btn-danger' %>
								</td>
							</tr>
						<% end %>
					<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
  <%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>

	<script>
		$(document).ready(spud.admin.post_categories.init);
	</script>
  <% if Spud::Blog.disqus_shortname %>
    <%= javascript_include_tag "//#{Spud::Blog.disqus_shortname}.disqus.com/count.js", :id => 'dsq-count-scr', :async => true %>
  <% end %>
<%end%>

app/views/admin/posts/new.html.erb
<%= form_for @post,
	url: admin_posts_path(),
	remote: true,
	data: {
		errors: :inline,
		success: admin_posts_path,
		preview_action: admin_post_preview_path(@post)
	},
	html: { class: "form-horizontal page_form" } do |f| %>
	<%= render :partial => 'form', :locals => {:f => f} %>
<% end %>